name: Snyk CI/CD Integration
on:
  push:
    branches:
      - main   # Analyse à chaque push sur la branche "main"
  pull_request:
    branches:
      - main   # Analyse pour chaque pull request sur "main"

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Assurez-vous que la version Java correspond à votre projet

      - name: Run Snyk test
        uses: snyk/actions/setup@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: mvn snyk:test --all-projects
